app:
  env: "dev"

logging:
  stdout: true
  level: "debug"

scheduler:
  name: random-scheduler
  namespace: random-scheduler
  algorithm: "cloud-first"
  informerSyncPeriod: "15s"
  edgeAnnotationKey: "momtaz/cluster-type"
  edgeAnnotationValue: "edge"

connector:
  mode: "outside"
  masterURL: "172.20.2.4"
  kubeConfigPath: "/Users/sinashariati/.kube/config"
